<?php

  #The URL root is the AWS meta data service URL where metadata
  # requests regarding the running instance can be made
  $urlRoot="http://169.254.169.254/latest/meta-data/";

  # Get the instance ID from meta-data and print to the screen
  $instance = file_get_contents($urlRoot . 'instance-id');

  # Availability Zone
  $az = file_get_contents($urlRoot . 'placement/availability-zone');

?>

<center><b>Yolo</b> This page was generated by instance <b><?= $instance ?></b> in Availability Zone <b><?= $az ?></b>.</center>

<!-- 
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/placement/availability-zone -->